import React from "react";

/* ── Linear Icons — stroke SVGs ── */
export const linearIcons: Record<string, React.ReactNode> = {
  대시보드: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("rect", { x: 1.5, y: 1.5, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 9.5, y: 1.5, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 1.5, y: 9.5, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 9.5, y: 9.5, width: 5, height: 5, rx: 1 }),
  ),
  주문: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("path", { d: "M4.5 1.5h7a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1h-7a1 1 0 0 1-1-1v-11a1 1 0 0 1 1-1z" }),
    React.createElement("line", { x1: 5.5, y1: 5, x2: 10.5, y2: 5 }),
    React.createElement("line", { x1: 5.5, y1: 7.5, x2: 10.5, y2: 7.5 }),
    React.createElement("line", { x1: 5.5, y1: 10, x2: 8.5, y2: 10 }),
  ),
  거래처: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("circle", { cx: 5.5, cy: 5, r: 2 }),
    React.createElement("path", { d: "M1.5 13.5c0-2.2 1.8-4 4-4s4 1.8 4 4" }),
    React.createElement("circle", { cx: 11, cy: 5, r: 1.5 }),
    React.createElement("path", { d: "M14.5 13.5c0-1.7-1.1-3.1-2.7-3.6" }),
  ),
  출고: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("path", { d: "M1.5 10.5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2" }),
    React.createElement("path", { d: "M1.5 10.5l2-6h9l2 6" }),
    React.createElement("circle", { cx: 4.5, cy: 13.5, r: 0 }),
    React.createElement("circle", { cx: 11.5, cy: 13.5, r: 0 }),
    React.createElement("line", { x1: 5, y1: 4.5, x2: 5, y2: 2 }),
    React.createElement("polyline", { points: "3.5 3.5 5 2 6.5 3.5" }),
  ),
  재고: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("path", { d: "M2.5 5.5l5.5-3 5.5 3v5l-5.5 3-5.5-3z" }),
    React.createElement("line", { x1: 8, y1: 8.5, x2: 8, y2: 13.5 }),
    React.createElement("line", { x1: 2.5, y1: 5.5, x2: 8, y2: 8.5 }),
    React.createElement("line", { x1: 13.5, y1: 5.5, x2: 8, y2: 8.5 }),
  ),
  수금: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5, strokeLinecap: "round", strokeLinejoin: "round" },
    React.createElement("rect", { x: 1.5, y: 3.5, width: 13, height: 9, rx: 1 }),
    React.createElement("line", { x1: 1.5, y1: 7, x2: 14.5, y2: 7 }),
    React.createElement("line", { x1: 4.5, y1: 10, x2: 7.5, y2: 10 }),
  ),
};

/* ── Notion Icons — emoji spans ── */
export const notionIcons: Record<string, React.ReactNode> = {
  대시보드: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "📊"),
  주문: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "📝"),
  거래처: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "👥"),
  출고: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "📦"),
  재고: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "🏬"),
  수금: React.createElement("span", { style: { fontSize: 16, lineHeight: 1 } }, "💳"),
};

/* ── Supabase Icons — stroke SVGs (different shapes from Linear) ── */
export const supabaseIcons: Record<string, React.ReactNode> = {
  대시보드: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("rect", { x: 2, y: 2, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 9, y: 2, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 2, y: 9, width: 5, height: 5, rx: 1 }),
    React.createElement("rect", { x: 9, y: 9, width: 5, height: 5, rx: 1 }),
  ),
  주문: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("rect", { x: 3, y: 1.5, width: 10, height: 13, rx: 1.5 }),
    React.createElement("line", { x1: 5.5, y1: 5, x2: 10.5, y2: 5 }),
    React.createElement("line", { x1: 5.5, y1: 7.5, x2: 10.5, y2: 7.5 }),
    React.createElement("line", { x1: 5.5, y1: 10, x2: 8.5, y2: 10 }),
  ),
  거래처: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("circle", { cx: 6, cy: 5, r: 2.5 }),
    React.createElement("path", { d: "M1.5 14c0-2.5 2-4.5 4.5-4.5s4.5 2 4.5 4.5" }),
    React.createElement("circle", { cx: 11.5, cy: 5.5, r: 1.8 }),
    React.createElement("path", { d: "M14.5 14c0-2 -1.3-3.5-3-3.5" }),
  ),
  출고: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("rect", { x: 1, y: 4, width: 10, height: 8, rx: 1 }),
    React.createElement("path", { d: "M11 7h2.5l1.5 2.5V12h-4" }),
    React.createElement("circle", { cx: 4, cy: 13, r: 1.5 }),
    React.createElement("circle", { cx: 12.5, cy: 13, r: 1.5 }),
  ),
  재고: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("path", { d: "M8 1.5L14 5v6l-6 3.5L2 11V5l6-3.5z" }),
    React.createElement("path", { d: "M8 8.5V15" }),
    React.createElement("path", { d: "M2 5l6 3.5L14 5" }),
  ),
  수금: React.createElement("svg", { width: 16, height: 16, viewBox: "0 0 16 16", fill: "none", stroke: "currentColor", strokeWidth: 1.5 },
    React.createElement("rect", { x: 1.5, y: 3.5, width: 13, height: 9, rx: 1.5 }),
    React.createElement("path", { d: "M1.5 7h13" }),
    React.createElement("rect", { x: 3.5, y: 9, width: 3, height: 1.5, rx: 0.5 }),
  ),
};

/* ── Notion Table Column-Property Icons — Notion property-type indicators ── */
export const notionTableIcons: Record<string, React.ReactNode> = {
  text: React.createElement(
    "span",
    { style: { fontSize: 12, lineHeight: 1, fontFamily: "var(--k-font-heading)", fontWeight: 600, color: "var(--k-text-muted)" } },
    "Aa",
  ),
  number: React.createElement(
    "span",
    { style: { fontSize: 13, lineHeight: 1, fontFamily: "var(--k-font-mono)", color: "var(--k-text-muted)" } },
    "#",
  ),
  date: React.createElement(
    "span",
    { style: { fontSize: 14, lineHeight: 1 } },
    "📅",
  ),
  status: React.createElement(
    "span",
    { style: { fontSize: 10, lineHeight: 1, color: "var(--k-text-muted)" } },
    "●",
  ),
  select: React.createElement(
    "span",
    { style: { fontSize: 10, lineHeight: 1, color: "var(--k-text-muted)" } },
    "▼",
  ),
  user: React.createElement(
    "span",
    { style: { fontSize: 14, lineHeight: 1 } },
    "👤",
  ),
};
